pshrmn/curi

- documentation-website/src/client/Packages/Core.js
- packages/core/CHANGELOG.md
- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/tests/curi.spec.ts
Currently, when you call `set.redirect` in `match.response`, the resulting response object will be emitted to all response handlers and then Curi will automatically redirect to the new location.
This PR adds a new option, `emitRedirects`, which defaults to `true`, but when it is is `false`, will not emit the redirect response.
```js
{
name: 'Profile',
path: 'u/:id',
match: {
response: ({ route, set, addons }) => {
// synchronous API to verify if user can view page
if(!user.canViewProfile(route.params.id) {
set.redirect(addons.pathname('Home'));
} else {
set.body(Profile);
}
}
}
}
```
The benefit of not emitting the response is that you do not have to care about what to render for that response.
```jsx
function render(response) {
if (response.redirectTo) {
// what should you render when …
```
> Add options.emitRedirects to @curi/core

- packages/core/CHANGELOG.md
- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/tests/curi.spec.ts
- packages/core/types/curi.d.ts
- packages/core/types/types/curi.d.ts
- packages/react-native/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/src/Curious.tsx
- packages/react/tests/Curious.spec.tsx
- packages/react/types/Curious.d.ts
While `router.respond` (even with `{ once: true }`) is a convenient way to do something once a response is emitted, it is also asynchronous. Sometimes you want to know what the current response is synchronously. The new method `current` returns an object with the `response` and `action` properties.
```js
const router = curi(history, routes);
const tooSoon = router.current();
// tooSoon.response === null
// tooSoon.action === null
router.respond((response, action) => {
const justRight = router.current();
// justRight.response === response;
// justRight.action === action;
});
```
> Add router.current method

- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/tests/curi.spec.ts
- packages/core/types/types/curi.d.ts
This can be used to register a response handler, but wait until the next response is emitted before it is called (instead of calling it immediately if there is a response).
The `<Curious>` component gets its initial `response` and `navigation` values by calling `router.current`. In its `componentDidMount` lifecycle method, it subscribes to the router so that it can update its `state` when new responses are emitted. However, it also calls `setState` immediately, which triggers an extra render. With `{ initial: false }`, `<Curious>` will not call `setState` until a new `response` is emitted.
> Add initial option to router.respond

- packages/react-native/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/src/Curious.tsx
- packages/react/tests/Curious.spec.tsx
Skip calling the response handler when a <Curious> component is mounted so that there isn't a double render.
> <Curious> resp handler not called on mount

- documentation-website/src/client/Examples/react/Authentication.js
- documentation-website/src/client/Examples/vue/Authentication.js
- documentation-website/src/client/Guides/AllAboutRoutes.js
- documentation-website/src/client/Guides/Loading.js
- packages/core/src/finishResponse.ts
- packages/core/src/types/route.ts
- packages/core/tests/curi.spec.ts
- packages/core/tests/route-matching.spec.ts
- packages/core/types/types/route.d.ts
The previous setup expected the user to provide the `pathname` themselves (or use the `pathname` add-on to genreate it). While add-ons are there for users to use, the new method should be easier and less error prone (you can only redirect to valid routes).
```js
// old
response({ set, route, addons }) {
const pathname = addons.pathname('Album', route.params);
set.redirect(pathname);
}
// new
response({ set, route }) {
set.redirect({ name: 'Album', params: route.params });
}
```
> Better set.redirect signature

- packages/core/CHANGELOG.md
- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/tests/curi.spec.ts
- packages/core/types/finishResponse.d.ts
- packages/core/types/types/curi.d.ts
- packages/core/types/types/route.d.ts
- packages/react-native/src/Link.tsx
- packages/react/src/Link.tsx
- packages/svelte/src/Link.html
- packages/svelte/tests/link.spec.js
- packages/vue/src/Link.ts
I've decided against adding a global router method. The only benefit this really had over using `router.addons.pathname` was that it would automatically fall back to the response's `location.pathname` if a `to` valid is not provided. However, the `<Link>`s can just grab this internally from the `response` (each has access to it, although how varies).
> Revert router.createLocation (#37)

- documentation-website/src/client/pages/Examples/react/Authentication.js
- documentation-website/src/client/pages/Examples/react/MultiBody.js
- documentation-website/src/client/pages/Examples/vue/Authentication.js
- documentation-website/src/client/pages/Guides/AllAboutRoutes.js
- documentation-website/src/client/pages/Guides/CodeSplitting.js
- documentation-website/src/client/pages/Guides/GettingStarted.js
- documentation-website/src/client/pages/Guides/Loading.js
- documentation-website/src/client/pages/Guides/MigrateReactRouterv3.js
- documentation-website/src/client/pages/Guides/ReactBasics.js
- documentation-website/src/client/pages/Guides/Responses.js
- documentation-website/src/client/pages/Packages/Core.js
- documentation-website/src/client/pages/Packages/SideEffectTitle.js
- documentation-website/src/client/pages/Tutorials/ReactBasics.js
- documentation-website/src/client/pages/Tutorials/VueBasics.js
- packages/core/CHANGELOG.md
- packages/core/src/finishResponse.ts
- packages/core/src/types/index.ts
- packages/core/src/types/response.ts
- packages/core/src/types/route.ts
- packages/core/tests/curi.spec.ts
- packages/core/tests/route-matching.spec.ts
- packages/core/types/types/index.d.ts
- packages/core/types/types/response.d.ts
- packages/core/types/types/route.d.ts
The `set` methods were a bit verbose. Instead, Curi will just use an object returned by `response()` to update the response that will be emitted.
```js
// before
response({ set }) {
set.body(Home);
set.data("Something or other");
}
// now
response() {
return {
body: Home,
data: "Yadda yadda"
};
}
```
Any invalid properties will be ignored.
`redirectTo` is transformed. It takes a route's `name` (and `params` if required) and generates a `pathname` which will be set on the response.
```js
response() {
return {
redirectTo: "Home"
};
}
// response = { redirectTo: { pathname: "/" }, ... }
```
> route.response() returns an object to modify the response

- documentation-website/src/client/pages/Guides/UsingSideEffects.js
- documentation-website/src/client/pages/Packages/SideEffectScroll.js
- documentation-website/src/client/pages/Packages/SideEffectTitle.js
- packages/core/CHANGELOG.md
- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/src/types/route.ts
- packages/core/tests/curi.spec.ts
- packages/core/tests/route-matching.spec.ts
- packages/core/types/types/curi.d.ts
- packages/core/types/types/route.d.ts
`fn` is vague, `effect` is more explicit.
```js
const scroll = createScrollSideEffect();
const router = curi(history, routes, {
sideEffects: [
{ effect: scroll, after: true }
]
});
```
> Side effect fn ->  effect

- .travis.yml
- documentation-website/src/client/pages/Guides/AllAboutRoutes.js
- packages/core/CHANGELOG.md
- packages/core/src/finishResponse.ts
- packages/core/src/resolveMatchedRoute.ts
- packages/core/src/types/index.ts
- packages/core/src/types/match.ts
- packages/core/src/types/response.ts
- packages/core/src/types/route.ts
- packages/core/src/utils/match.ts
- packages/core/tests/route-matching.spec.ts
- packages/core/types/finishResponse.d.ts
- packages/core/types/types/index.d.ts
- packages/core/types/types/match.d.ts
- packages/core/types/types/response.d.ts
- packages/core/types/types/route.d.ts
- packages/interactions/route-prefetch/CHANGELOG.md
- packages/interactions/route-prefetch/src/index.ts
1. Re-grouped the `name`, `params`, and `location` passed to `route.response()` under `match`. `match` also contains the `partials` array of partial matches (any ancestors of the matched route) and the `key` of the `location` (probably not useful, but used to uniquely identify the response).
```js
{
response({ match }) {
const { name, params, location, key, partials } = match;
}
}
```
2. Removed the `route` interactions from being passed to `route.response()`. The initial reason these were added was to generate the pathname of a location to redirect to. That is now handled for the user when they provide the `name`/`params` to `redirectTo`. The `active` and `prefetch` interactions don't make sense to use here. The `ancestors` interaction is covered by `match.partials`. Custom interactions …
> One more route.response() cleanup

- documentation-website/src/client/pages/Packages/Core.js
- documentation-website/src/client/pages/Tutorials/ReactBasics.js
- documentation-website/src/client/pages/Tutorials/VueBasics.js
- package-lock.json
- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/tests/curi.spec.ts
- packages/core/types/types/curi.d.ts
- packages/core/types/utils/async.d.ts
- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/types/Link.d.ts
- packages/react/CHANGELOG.md
- packages/react/package-lock.json
- packages/react/src/Link.tsx
- packages/react/types/Link.d.ts
- packages/vue/package-lock.json
- packages/vue/tests/plugin.spec.ts
`router.navigate()` lets the user navigate using a route's `name`/`params`. This is really just a shortcut for using the `pathname` route interaction, but more convenient.
`@curi/vue` and `@curi/svelte` still use `router.history.navigate()` because they have to compute the `location` for the `href`, so they might as well re-use it.
Closes #44
> Add router.navigate() method

- documentation-website/src/client/pages/Guides/Responses.js
- documentation-website/src/client/pages/Home/index.js
- documentation-website/src/client/pages/Tutorials/ReactBasics.js
- documentation-website/src/client/pages/Tutorials/VueBasics.js
- packages/core/CHANGELOG.md
- packages/core/src/types/response.ts
- packages/core/src/utils/match.ts
- packages/core/tests/route-matching.spec.ts
- packages/core/types/types/response.d.ts
`response.key` was just an alias for `response.location.key`. This property isn't particularly useful except for some small things (i.e. animation keys), so it doesn't warrant its own top-level property.
> Remove response.key

- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/tests/Link.spec.tsx
- packages/react/CHANGELOG.md
- packages/react/src/Active.tsx
- packages/react/src/Link.tsx
- packages/react/tests/Active.spec.tsx
- packages/react/tests/Link.spec.tsx
- packages/react/types/Link.d.ts
Use `React.forwardRef()` to forward link refs to "host" component.
```jsx
// @curi/react
const ref = React.createRef();
<Link to="Home" ref={ref}>Home</Link>
// ref.current = <a href="/">Home</a>
```
> React(-Native) <Link>s forward ref

- packages/react/CHANGELOG.md
- packages/react/src/Prefetch.tsx
- packages/react/src/index.ts
- packages/react/tests/Prefetch.spec.tsx
- packages/react/types/Prefetch.d.ts
- packages/react/types/index.d.ts
This makes the resolved object available once data for the route has been prefetched. Useful for adding an indicator once the data has been prefetched or even filling in data for a thumbnail.
```jsx
<Prefetch match={{ name: "User", params: { id: 1 } }}>
{(ref, resolved) => (
<Link to="User" params={{ id: 1 }} ref={ref}>
User 1 {resolved ? "✓" : "..."}
</Link>
)}
</Prefetch>
```
> Add resolved object as second arg to <Prefetch> children

- packages/react/CHANGELOG.md
- packages/react/src/Prefetch.tsx
- packages/react/tests/Prefetch.spec.tsx
Help to catch when you forget to pass the `ref` to a component.
```jsx
<Prefetch>
{ref => <div>...</div>}
</Prefetch>
// Warning: The ref provided to the children function is null.
// Did you forget to pass it to a component?
```
> Warn when <Prefetch> ref is null

- packages/core/CHANGELOG.md
- packages/core/src/curi.ts
- packages/core/src/types/curi.ts
- packages/core/tests/curi.spec.ts
- packages/core/types/types/curi.d.ts
- packages/react/CHANGELOG.md
- packages/react/src/Link.tsx
- packages/react/tests/Link.spec.tsx
- packages/react/types/Link.d.ts
- packages/vue/CHANGELOG.md
- packages/vue/src/Link.ts
- packages/vue/tests/Link.spec.ts
- packages/vue/types/Link.d.ts
These functions provide escape hatches to render showing navigation status.
`finished` is a function that will be called once the navigation has been completed.
`cancelled` is a function that will be called if a navigation is cancelled (because another navigation superseded it).
```js
router.navigate({
name: "User",
params: { id: 1 },
cancelled: () => {
// update UI to acknowledge link is no longer navigation
},
finished: () => {
// update UI to acknowledge link has finished navigating
// this is mostly useful for persistent links
}
})
```
This PR also make @curi/react's `<Link>` `children` an optional render-invoked prop. If `children` is a function, it will be called with the `<Link>`'s `loading` state (default `false`, `true` while navigating, `false` after navigation finishes or is …
> Add cancelled/finished callbacks to router.navigate()

- packages/vue/CHANGELOG.md
- packages/vue/scripts/build.js
- packages/vue/src/focus.ts
- packages/vue/src/plugin.ts
- packages/vue/tests/focus.spec.ts
- packages/vue/types/focus.d.ts
- website/src/client/pages/Packages/Vue.js
A Vue directive to automatically focus an element when new responses are emitted.
```html
<main :tabIndex="-1" v-curi-focus="$curi.response">
<component :is="$curi.response.body" />
</main>
```
Warns if the element the directive is attached to isn't natively-focusable or doesn't have a `tabIndex` of `-1` set on it.
The current `response` is passed to the directive so that it can detect when there is a new response and re-focus.
> Add Vue curi-focus directive

- packages/react/CHANGELOG.md
- packages/react/src/CuriProvider.tsx
- packages/react/tests/CuriProvider.spec.tsx
- packages/react/types/CuriProvider.d.ts
While the user should generally always use the same router, they can now pass the `<CuriProvider>` a new router and the component will stop observing the old router and start observing the new router.
> Allow <CuriProvider> to receive a new router prop

- packages/router/CHANGELOG.md
- packages/router/src/curi.ts
- packages/router/tests/curi.spec.ts
Previously, a new response would not be emitted after calling `replaceRoutes()` until a new navigation occurs. Now, a new response is emitted immediately so that the application re-renders using a response generated from the new routes.
> Emit new response after updating routes

- packages/react/CHANGELOG.md
- packages/react/src/CuriProvider.tsx
- packages/react/types/CuriProvider.d.ts
- packages/router/CHANGELOG.md
- packages/router/src/types/index.ts
- packages/router/types/types/index.d.ts
With Suspense, the `<CuriProvider>` will need to store the `response` (and `navigation`) in state instead of reading from the router.
> Prep <CuriProvider> for suspense

- packages/interactions/route-active/CHANGELOG.md
- packages/interactions/route-active/scripts/build.js
- packages/interactions/route-ancestors/CHANGELOG.md
- packages/interactions/route-ancestors/scripts/build.js
- packages/interactions/route-prefetch/CHANGELOG.md
- packages/interactions/route-prefetch/scripts/build.js
- packages/react/CHANGELOG.md
- packages/react/scripts/build.js
- packages/router/CHANGELOG.md
- packages/router/scripts/build.js
- packages/side-effects/side-effect-aria-live/CHANGELOG.md
- packages/side-effects/side-effect-aria-live/scripts/build.js
- packages/side-effects/side-effect-scroll/CHANGELOG.md
- packages/side-effects/side-effect-scroll/scripts/build.js
- packages/side-effects/side-effect-title/scripts/build.js
- packages/vue/CHANGELOG.md
- packages/vue/scripts/build.js
This is primarily being done so that the builds intended for `<script>` tags can be tested.
> Moving scripts to UMD instead of IIFE

- packages/react-native/jest.config.js
- packages/react-native/package-lock.json
- packages/react-native/package.json
Jest still uses babel internally for its tests, but there is no need to explicitly include them.
> Drop explicit @curi/react-native babel deps

- packages/router/CHANGELOG.md
- packages/router/src/interactions/pathname.ts
- packages/router/src/matchLocation.ts
- packages/router/src/route.ts
- packages/router/tests/route-matching.spec.ts
Previously, a path whose initial segment is optional (`:lang?/about`) would fail when the initial segment wasn't provided. This switches the internals to compile the path (via `path-to-regexp`) with a leading slash.
> Fix for optional initial path segment

- packages/react-dom/CHANGELOG.md
- packages/react-dom/src/Focus.tsx
- packages/react-dom/tests/Focus.spec.tsx
- packages/react-dom/types/Focus.d.ts
Enables the [experimental `preventScroll` option](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#Parameters) for the focused element.
> <Focus preventScroll={true}>

- packages/side-effects/side-effect-title/CHANGELOG.md
- packages/side-effects/side-effect-title/src/index.ts
- packages/side-effects/side-effect-title/tests/createTitleSideEffect.spec.ts
- packages/side-effects/side-effect-title/types/index.d.ts
- website/src/client/index.js
Instead of specifying prefixes, suffixes, and delimiters, the side effect takes a `callback()` function, which will be passed the emitted object. The results of the `callback()` function will be set as the document's `title`.
```js
import createTitleSideEffect from "@curi/side-effect-title";
const setTitle = createTitleSideEffect(({ response }) => `My Site | ${response.title}`);
```
> Simplify @curi/side-effect-title

- packages/router/CHANGELOG.md
- packages/router/src/curi.ts
- packages/router/tests/curi.spec.ts
Previously, refreshing would emit a `navigation.previous` that was the most recent `response`. Now, refreshing will emit a `navigation.previous` that was the most recent `navigation.previous`.
> Re-use navigation.previous when refreshing

- packages/react-dom/tests/Link.spec.tsx
- packages/react-native/tests/Link.spec.tsx
- packages/react-universal/src/curiProvider.tsx
- packages/react-universal/tests/Curious.spec.tsx
- packages/react-universal/tests/curiProvider.spec.tsx
- packages/router/CHANGELOG.md
- packages/router/src/curi.ts
- packages/router/src/types/curi.ts
- packages/router/src/types/index.ts
- packages/router/tests/curi.spec.ts
- packages/router/tests/path.spec.ts
- packages/router/tests/route-matching.spec.ts
- packages/router/types/types/curi.d.ts
- packages/router/types/types/index.d.ts
- packages/svelte/src/store.js
- packages/svelte/tests/link.spec.js
- packages/svelte/tests/store.spec.js
- packages/vue/src/plugin.ts
- packages/vue/tests/Link.spec.ts
- packages/vue/tests/plugin.spec.ts
Previously, one function was used for setting up response handlers. The exact functionality was determined using an `options` object.
Now, the two functionalities are split into their own respective methods.
While this adds to the API surface area, it should also be easier to document.
```js
// setting up an observer
// old
const stop = router.respond(fn, { observe: true });
// new
const stop = router.observe(fn);
// setting up a one time function
// old
router.respond(fn);
// new
router.once(fn);
```
> Split router.respond() into once() and observe()

- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/curi.ts
- packages/router/src/types/curi.ts
- packages/router/tests/curi.spec.ts
- packages/router/types/types/curi.d.ts
- website/src/client/pages/Packages/Router.js
This is primarily a server side rendering feature.
With automatic redirects and synchronous routes, calling `router.once()` (or `observe()`) will occur after the redirect, so the response handler is called with the redirected location's `response`. This is fine on the client side where the response handler only cares about the most up-to-date location, but on the server, `once()` should be called with the real first `response`.
> Add automaticRedirects option to router

- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/matchLocation.ts
- packages/router/tests/route-matching.spec.ts
Previously, when a parent route ended with a slash, the children route would be matched against a pathname that had no leading slash.
This bug was probably introduced in #100, which fixed an issue with optional parameters and required switching to testing against routes against pathnames with leading slashes.
> Fix bug when parent route ends with slash

- packages/static/.size-snapshot.json
- packages/static/CHANGELOG.md
- packages/static/src/staticFiles.ts
- packages/static/tests/staticFiles.spec.ts
Previously, only errors thrown by synchronous routes were caught because the `try...catch` wrapped `router.once()`, so it would only catch errors that occur when `router.once()` was called immediately.
> [static] Catch errors thrown by async routes

- packages/interactions/route-active/.size-snapshot.json
- packages/interactions/route-active/src/index.ts
- packages/interactions/route-ancestors/.size-snapshot.json
- packages/interactions/route-ancestors/src/index.ts
- packages/interactions/route-prefetch/.size-snapshot.json
- packages/interactions/route-prefetch/src/index.ts
- packages/router/.size-snapshot.json
- packages/router/src/curi.ts
- packages/static/.size-snapshot.json
- packages/static/src/pathnames.ts
Wrap `console.warn()`/`console.error()` in a `NODE_ENV` check so that they can be stripped out in production.
> Wrap console logs in dev check

- packages/vue/.size-snapshot.json
- packages/vue/CHANGELOG.md
- packages/vue/src/focus.ts
- packages/vue/src/index.ts
- packages/vue/tests/focus.spec.ts
- packages/vue/types/focus.d.ts
- packages/vue/types/index.d.ts
Instead of passing a unique object to the directive, pass an object with `key`, `preserve` and `preventScroll`  properties.
When the `key` changes, the element will be re-focused.
When `preserve` is `true` (default `false`), the element will not be focused if one of its children is already focused.
When `preventScroll` is `true` (default `false`), the element will not be scrolled to when it is focused (requires browser support for the option).
> Improve v-curi-focus

- packages/react-universal/.size-snapshot.json
- packages/react-universal/CHANGELOG.md
- packages/react-universal/src/curiProvider.tsx
- packages/react-universal/types/curiProvider.d.ts
Previously, a new object was created every time the `curiProvider()`'s component's `render()` function was called. Now, this object is stored in state so that it is re-used for re-renders not triggered by new responses.
> Re-use state object for curiProvider() component's context

- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/src/Link.tsx
- packages/react-dom/tests/Link.spec.tsx
- packages/react-native/.size-snapshot.json
- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/tests/Link.spec.tsx
If the `<Link>` unmounts before navigation is finished, it shouldn't call `setState()`.
> Don't call setState() for unmounted Links

- packages/interactions/route-active/package-lock.json
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/curi.ts
- packages/router/src/finishResponse.ts
- packages/router/src/resolveMatchedRoute.ts
- packages/router/src/types/curi.ts
- packages/router/src/types/route.ts
- packages/router/tests/curi.spec.ts
- packages/router/tests/route-matching.spec.ts
- packages/router/types/finishResponse.d.ts
- packages/router/types/resolveMatchedRoute.d.ts
- packages/router/types/types/curi.d.ts
- packages/router/types/types/route.d.ts
- website/src/pages/Guides/apollo.js
- website/src/pages/Packages/router.js
Currently, there isn't a good way to access some types of values in routes, especially runtime ones.
For example, if you are using a store (Apollo, Redux), you _could_ import it in the module where the routes are defined, but this requires the store to be created in its own module. If the store is dynamically initialized, this breaks down quickly.
Rendering on the server can also be painful. If the route wants to know about a request's cookies or the authenticated user, how does it access this information?
This PR introduces a `external` option when creating a router.
```js
const client = new ApolloClient({...});
const router = curi(history, routes, {
external: {
apollo: client
}
});
```
The `external` value will be available to a route's `resolve` functions through their second argument. …
> Provide external values when creating router

- examples/react/async-nav/src/index.js
- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-native/CHANGELOG.md
- packages/react-universal/.size-snapshot.json
- packages/react-universal/CHANGELOG.md
- packages/react-universal/src/Navigating.tsx
- packages/react-universal/src/index.ts
- packages/react-universal/tests/Navigating.spec.tsx
- packages/react-universal/types/Navigating.d.ts
- packages/react-universal/types/index.d.ts
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/curi.ts
- packages/router/src/types/curi.ts
- packages/router/src/types/index.ts
- packages/router/tests/curi.spec.ts
- packages/router/types/types/curi.d.ts
- packages/router/types/types/index.d.ts
- website/src/pages/Packages/react-dom.js
- website/src/pages/Packages/react-native.js
- website/src/pages/Packages/router.js
The one downside of async navigation is that the user is unable easily to cancel navigation. Currently, they either have to refresh the page or click a link to the same location as the current one.
This PR lets you pass an observer to the `router` through a new `cancel()` method. The observer will be called when navigation starts and when the navigation finishes (either because it actually finishes or because it was cancelled). When navigation starts, the observer will be passed a `cancel` function; calling that function will cancel the navigation. When the navigation is finished, the observer will be passed `undefined`.
```js
function observer(fn) {
// fn is a function while navigating and undefined while it is not
}
router.cancel(observer);
```
A `<Navigating>` component is added to all …
> Make async navigation cancellable

- package-lock.json
- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/package.json
- packages/react-dom/src/Link.tsx
- packages/react-dom/tests/Link.spec.tsx
- packages/react-dom/types/Link.d.ts
- packages/react-native/.size-snapshot.json
- packages/react-native/CHANGELOG.md
- packages/react-native/package-lock.json
- packages/react-native/package.json
- packages/react-native/src/Link.tsx
- packages/react-native/types/Link.d.ts
- website/src/pages/Packages/react-dom.js
- website/src/pages/Packages/react-native.js
The first change this makes is that `Link` is no longer a "pure" component (`React.PureComponent`). Instead, a more refined `shouldComponentUpdate` check is used so that re-using params objects does not cause unnecessary re-renders.
The second change is only for `@curi/react-dom`. The generated `href` is now relative (no `pathname`) when the `to` prop is not provided. Previously, the `location.pathname` of the current response was used. The new `href` is functionally equivalent to the old approach, but the `Link` no longer requires knowledge of the current `response`. (The `href` isn't even used when navigating within the application.)
```jsx
<Link hash="#test">Test</Link>
// old
<a href="/current-location#test">Test</a>
// new
<a href="#test">Test</a>
```
> Tweak @curi/react-dom & @curi/react-native Link components

- package-lock.json
- packages/react-dom/src/Link.tsx
- packages/react-dom/types/Link.d.ts
- packages/react-native/src/Link.tsx
- packages/react-native/types/Link.d.ts
- packages/react-universal/src/Block.tsx
- packages/react-universal/src/curiProvider.tsx
- packages/react-universal/types/Block.d.ts
- packages/react-universal/types/curiProvider.d.ts
* Don't need to expose private interfaces.
* Set a return type for `curiProvider()`.
> Remove unnecessary type exports

- packages/svelte/src/Link.html
- packages/svelte/tests/cases/link/forward-props/app.html
- packages/svelte/tests/cases/link/forward-props/index.js
- packages/svelte/tests/link.spec.js
Any properties of the `forward` object will be passed to the rendered anchor. This is the same API as the React packages. 
```html
<Link name="Home" forward={{ class: "active" }}>Home</Link>
<a href="/" class="active">Home</a>
```
> Svelte <Link forward> passes props to <a>

- packages/static/.size-snapshot.json
- packages/static/src/staticFiles.ts
- packages/static/src/types.ts
- packages/static/tests/staticFiles.spec.ts
- packages/static/types/types.d.ts
- website/src/pages/Packages/static.js
This will create a page with the given filename (path generated using `output.dir`) of content generated by navigating to the `pathname`. This is useful for statically hosted sites that support a specific fallback URL (e.g. Netlify uses `404.html`).
```js
staticFiles({
fallback: {
filename: "404.html",
pathname: "/404"
},
});
```
> Generate 404 page with @curi/static

- packages/interactions/route-prefetch/.size-snapshot.json
- packages/interactions/route-prefetch/types/index.d.ts
- packages/router/.size-snapshot.json
- packages/router/src/curi.ts
- packages/router/src/prepareRoutes.ts
- packages/router/src/types/curi.ts
- packages/router/src/types/index.ts
- packages/router/src/types/route.ts
- packages/router/tests/curi.spec.ts
- packages/router/types/curi.d.ts
- packages/router/types/prepareRoutes.d.ts
- packages/router/types/types/curi.d.ts
- packages/router/types/types/index.d.ts
- packages/router/types/types/route.d.ts
- packages/vue/tests/focus.spec.ts
Removes the ability to pass a raw (unprepared) array of routes to `curi()`.
`prepareRoutes` must now be used to prepare the array of routes.
```js
import { prepareRoutes } from "@curi/router";
const routes = prepareRoutes([
{ name: "Home", path: "" },
// ...
]);
const router = curi(history, routes);
```
> Routes array must be prepared

- packages/react-dom/.size-snapshot.json
- packages/react-dom/src/hooks/useNavigationFocus.ts
- packages/react-dom/tests/Focus.spec.tsx
- packages/react-dom/tests/useNavigationFocus.spec.tsx
- packages/react-universal/.size-snapshot.json
- packages/react-universal/src/curiProvider.tsx
- packages/react-universal/src/hooks/useBlock.ts
- packages/react-universal/src/hooks/useNavigating.ts
- packages/react-universal/tests/Block.spec.tsx
- packages/react-universal/tests/Navigating.spec.tsx
- packages/react-universal/tests/curiProvider.spec.tsx
- packages/react-universal/tests/useBlock.spec.tsx
- packages/react-universal/tests/useNavigating.spec.tsx
- packages/react-universal/tests/utils/wait.ts
`useLayoutEffect` was previously used because it is easier to test. The tests now use timeouts to wait until after a hook has run.
> Use the useEffect hook

- packages/interactions/route-active/.size-snapshot.json
- packages/interactions/route-active/src/index.ts
- packages/interactions/route-active/tests/active.spec.ts
- packages/interactions/route-active/types/index.d.ts
- packages/react-dom/.size-snapshot.json
- packages/react-universal/.size-snapshot.json
- packages/react-universal/package.json
- packages/react-universal/src/hooks/useActive.ts
- packages/react-universal/tests/useActive.spec.tsx
- packages/react-universal/types/hooks/useActive.d.ts
- website/src/pages/Guides/history.js
- website/src/pages/Packages/react-dom/v2/api/useActive.js
- website/src/pages/Packages/react-native/v2/api/useActive.js
- website/src/pages/Packages/route-active/v2/api/active.js
- website/src/pages/Tutorials/react-basics.js
Group the optional arguments to the `active` interaction in an options object.
```js
const isActive = router.route.active("Article", response, {
params: { id: "123" },
partial: false,
locationCheck: (loc) => loc.hash === "comments"
});
```
> Move optional active() arguments to object

- packages/react-dom/.size-snapshot.json
- packages/react-dom/src/Link.tsx
- packages/react-native/.size-snapshot.json
- packages/react-native/src/Link.tsx
- packages/react-universal/.size-snapshot.json
- packages/react-universal/src/hooks/useNavigationHandler.ts
- packages/react-universal/types/hooks/useNavigationHandler.d.ts
`useNavigationHandler` keeps track of `navigating` state itself, calls the `children` function (if it is a function), and cancels the current navigation if it unmounts while the navigation is active.
> Move more Link functionality to useNavigationHandler

- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/src/Link.tsx
- packages/react-dom/src/index.ts
- packages/react-dom/tests/Link.spec.tsx
- packages/react-dom/tests/NavLink.spec.tsx
- packages/react-dom/types/Link.d.ts
- packages/react-dom/types/index.d.ts
- packages/react-native/.size-snapshot.json
- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/src/index.ts
- packages/react-native/tests/Link.spec.tsx
- packages/react-native/tests/NavLink.spec.tsx
- packages/react-native/types/Link.d.ts
- packages/react-native/types/index.d.ts
- packages/react-universal/.size-snapshot.json
- packages/react-universal/CHANGELOG.md
- packages/react-universal/src/hooks/useNavigationHandler.ts
- packages/react-universal/src/index.ts
- packages/react-universal/tests/useNavigationHandler.spec.tsx
- packages/react-universal/tests/useStatefulNavigationHandler.spec.tsx
- packages/react-universal/types/hooks/useNavigationHandler.d.ts
- packages/react-universal/types/index.d.ts
The `useNavigationHandler` hook is split into two hooks: `useNavigationHandler`, which does not track navigating state and `useStatefulNavigationHandler`, which tracks navigating state.
The `Link` uses `useNavigationHandler` and expects its `children` prop to be a valid React node.
The `NavLink` uses `useStatefulNavigationhandler` and expects its `children` prop to be a function that receives the component's `navigating` state.
Both the `@curi/react-dom` and `@curi/react-native` packages export `Link` and `NavLink`.
```jsx
<Link name="Test">Test</Link>
<NavLink name="Test">
{navigating => (
<div>{navigating ? "Is Navigating" : "Not Navigating"}</div>
)}
</NavLink>
```
The `NavLink` is only useful for asynchronous routes. If a route has no `resolve` method, there is no reason to display …
> Split Link components into Link/NavLink

- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/src/Link.tsx
- packages/react-dom/src/index.ts
- packages/react-dom/tests/AsyncLink.spec.tsx
- packages/react-dom/types/Link.d.ts
- packages/react-dom/types/index.d.ts
- packages/react-native/.size-snapshot.json
- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/src/index.ts
- packages/react-native/tests/AsyncLink.spec.tsx
- packages/react-native/types/Link.d.ts
- packages/react-native/types/index.d.ts
- packages/react-universal/tests/useStatefulNavigationHandler.spec.tsx
I like the name `AsyncLink` slightly more because it refers to the link being used when navigating to async content.
> Rename NavLink to AsyncLink

- package-lock.json
- package.json
- packages/interactions/route-active/package.json
- packages/react-dom/tests/AsyncLink.spec.tsx
- packages/react-dom/tests/Link.spec.tsx
- packages/react-native/package.json
- packages/react-native/tests/AsyncLink.spec.tsx
- packages/react-native/tests/Link.spec.tsx
- packages/react-universal/package.json
- packages/react-universal/tests/curiProvider.spec.tsx
- packages/react-universal/tests/useNavigationHandler.spec.tsx
- packages/react-universal/tests/useStatefulNavigationHandler.spec.tsx
- packages/router/.size-snapshot.json
- packages/router/package.json
- packages/router/src/curi.ts
- packages/router/tests/curi.spec.ts
- packages/router/tests/route-matching.spec.ts
- packages/router/types/curi.d.ts
- packages/static/package.json
- packages/svelte/tests/cases/link/click/index.js
- packages/svelte/tests/cases/link/mod-click/index.js
- packages/svelte/tests/cases/link/not-left-click/index.js
- packages/svelte/tests/cases/link/prevent-click/index.js
- packages/svelte/tests/store.spec.js
- packages/vue/package.json
- packages/vue/tests/Link.spec.ts
- website/package.json
The `curi` function is passed a pending history, not a history. This is only a breaking change if an application was using the `history` instance outside of the router. Any code can be adapted to use `router.history` (although any direct usage of the `history` object should be limited).
> Use pending history

- packages/react-dom/.size-snapshot.json
- packages/react-dom/src/hooks/useNavigationFocus.ts
`useEffect` is called after the render, so we do not need to delay focusing.
> Set focus immediately in effect

- packages/router/src/match_location.ts
- packages/router/tests/route-matching.spec.ts
- packages/router/tests/route.spec.ts
If no function is provided for parsing a param, assume that it should be parsed using `decodeURIComponent`.
```js
{
name: "Example",
path: "e/:one/:two",
params: {
two: n => n
}
}
// location.pathname === "/e/Beyonc%C3%A9/Beyonc%C3%A9"
params = {
one: "Beyoncé", // no parser provided, so decodeURIComponent was used
two: "Beyonc%C3%A9"
}
```
> Automatically decode params if no fn is provided

- packages/router/.size-snapshot.json
- packages/router/src/create_router.ts
- packages/router/src/interactions/pathname.ts
- packages/router/src/prepare_routes.ts
- packages/router/tests/path.spec.ts
- packages/router/tests/route-matching.spec.ts
- packages/router/types/interactions/pathname.d.ts
- packages/types/src/index.ts
- packages/types/types/index.d.ts
- website/src/pages/Guides/routes.js
- website/src/pages/Packages/router/v2/api/curi.js
- website/src/pages/Packages/router/v2/api/route-objects.js
Instead of `route.path_options` taking the options for creating a regexp, it is now an object with two possible properties: `match` and `compile`.
The `match` property is the old `route.path_options`; it is used to pass options for creating a regular expression from the `path`.
The `compile` property is used to pass a custom `encode` function to be used when compiling a `pathname`. This used to be an option passed to `create_router`, but that has been removed. While this new setup is slightly less convenient because it has to be passed to each route, the option should almost never be used.
```js
{
name: "My Route",
path: "my/:item",
path_options: {
match: {
sensitive: false
},
compile: {
encode: (value, token) => value
}
}
}
```
> Move all path-to-regexp options to routes

- examples/misc/server-rendering/src/index.js
- examples/react/redirects/src/index.js
- examples/svelte/redirects/src/index.js
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/createRouter.ts
- packages/router/tests/curi.spec.ts
- packages/static/.size-snapshot.json
- packages/static/src/staticFiles.ts
- packages/types/src/index.ts
- packages/types/types/index.d.ts
- website/src/pages/Examples/react/redirects.js
- website/src/pages/Examples/svelte/redirects.js
- website/src/pages/Examples/vue/redirects.js
- website/src/pages/Guides/loading.js
- website/src/pages/Guides/responses.js
- website/src/pages/Guides/ssr.js
- website/src/pages/Packages/router/v1/api/curi.js
- website/src/pages/Packages/router/v2/api/curi.js
- website/src/pages/Packages/static/v1/api/staticFiles.js
- website/src/router.js
- website/src/routes/packages/index.js
Same behavior, but swapping defaults (`emitRedirects` defaulted to `true` while `invisibleRedirects` defaults to `false`).
> emitRedirects -> invisibleRedirects

- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/src/Link.tsx
- packages/react-dom/tests/AsyncLink.spec.tsx
- packages/react-dom/tests/Link.spec.tsx
- packages/react-native/.size-snapshot.json
- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/tests/AsyncLink.spec.tsx
- packages/react-native/tests/Link.spec.tsx
- packages/react-native/types/Link.d.ts
- packages/svelte/CHANGELOG.md
- packages/svelte/src/Link.html
- packages/svelte/tests/cases/link/forward-overwrite/app.html
- packages/svelte/tests/cases/link/forward-overwrite/index.js
- packages/svelte/tests/cases/link/forward-props/app.html
- packages/svelte/tests/link.spec.js
This change prevents the `forward` prop from taking precedence over props set by the components.
> Link components spread forward props before native props

- packages/side-effects/side-effect-aria-live/.size-snapshot.json
- packages/side-effects/side-effect-aria-live/CHANGELOG.md
- packages/side-effects/side-effect-aria-live/src/index.ts
Use the hiding technique from https://hugogiraudel.com/2016/10/13/css-hide-and-seek/ for the `aria-live` element inserted by a `@curi/side-effect-aria-live` announcer.
Fixes #193.
> Use RTL-friendly hide for aria-live announcer

- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/prepare/createRoute.ts
- packages/router/src/prepare/matchLocation.ts
- packages/router/src/router/createRouter.ts
- packages/router/tests/path.spec.ts
The new path matching code should be easier to understand as well as faster. Param mapping is delayed until we know that it is necessary.
The path matching tests are also expanded to ensure that routes with children routes work correctly.
> Improve route matching

- packages/react-dom/.size-snapshot.json
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/router/finishResponse.ts
- packages/router/tests/curi.spec.ts
- packages/router/tests/route.spec.ts
- packages/side-effects/side-effect-title/tests/createTitleSideEffect.spec.ts
- packages/static/.size-snapshot.json
- packages/types/CHANGELOG.md
- packages/types/src/index.ts
- packages/types/types/index.d.ts
This PR removes the `title`, `status`, and `error` properties from a response and adds a `meta` property.
The `meta` property is intended for non-rendered data, whereas the `data` property is intended for content that will be rendered by the application. This isn't a hard and fast rule, but a means of organizing information.
For example, a page's `title` and `status` would probably be put in a `meta` object. Additional properties, like a page's description (for use with `<meta name="Description">` for server-side/static-content rendering) would also be put on the `meta`.
Data loaded from a database would be put on the `data` object.
The `error` could either be put on the `data` or the `meta` depending on what you plan to do with it. If it will be rendered within the application as an …
> Add meta property to responses & always set body/data/meta

- packages/react-dom/tests/useNavigationFocus.spec.tsx
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/prepare/createRoute.ts
- packages/router/src/router/finishResponse.ts
- packages/router/tests/curi.spec.ts
- packages/router/tests/route.spec.ts
- packages/static/tests/staticFiles.spec.ts
- packages/types/CHANGELOG.md
- packages/types/src/index.ts
- packages/types/types/index.d.ts
This gets rid of the confusing `response` function and `response` object wording. `respond` is also an action verb, like `resolve`, which describes what the function does.
```js
// before
{
name: "Home",
path: "",
response() {
return { body: Home };
}
}
// after
{
name: "Home",
path: "",
respond() {
return { body: Home };
}
}
```
> Rename route.response to route.respond

- packages/helpers/rollup.config.js
- packages/interactions/route-ancestors/rollup.config.js
- packages/interactions/route-prefetch/rollup.config.js
- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/rollup.config.js
- packages/react-universal/rollup.config.js
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/rollup.config.js
- packages/side-effects/side-effect-aria-live/rollup.config.js
- packages/side-effects/side-effect-scroll/rollup.config.js
- packages/side-effects/side-effect-title/rollup.config.js
- packages/vue/.size-snapshot.json
- packages/vue/CHANGELOG.md
- packages/vue/rollup.config.js
- utils/rollup-plugins.js
For minified UMD builds, properly escape `"production"` so that the code is actually removed.
For non-minified UMD builds, replace `process.env.NODE_ENV` with `"development"`.
> Fix UMD builds

- packages/react-dom/tests/AsyncLink.spec.tsx
- packages/react-dom/tests/Link.spec.tsx
- packages/react-native/tests/AsyncLink.spec.tsx
- packages/react-native/tests/Link.spec.tsx
- packages/react-universal/tests/useURL.spec.tsx
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/router/createRouter.ts
- packages/router/tests/curi.spec.ts
- packages/svelte/tests/cases/link/relative/index.js
- packages/svelte/tests/link.spec.js
- packages/vue/tests/AsyncLink.spec.ts
- packages/vue/tests/Link.spec.ts
When using `router.url` with no name property, the URL returned will have no `pathname` component. If the history is configured with a `base`, that will not be included either.
```js
const url = router.url({ hash: "comments" });
// url = "#comments"
```
When navigating using a URL with no `pathname` component, the corresponding location will re-use the current location's `pathname`.
```js
const router = createRouter(inMemory, routes, {
history: {
locations: [{ url: "/initial-location" }]
}
});
const url = router.url({ hash: "comments" });
router.navigate({ url });
const { response } = router.current();
// response.location = { pathname: "/initial-location", hash: "comments", ... }
```
> router.url with no name returns relative URL

- packages/helpers/rollup.config.js
- packages/interactions/route-ancestors/rollup.config.js
- packages/interactions/route-prefetch/rollup.config.js
- packages/react-dom/rollup.config.js
- packages/react-native/rollup.config.js
- packages/react-universal/rollup.config.js
- packages/router/rollup.config.js
- packages/side-effects/side-effect-aria-live/rollup.config.js
- packages/side-effects/side-effect-scroll/rollup.config.js
- packages/side-effects/side-effect-title/rollup.config.js
- packages/static/rollup.config.js
- packages/svelte/rollup.config.js
- packages/vue/rollup.config.js
- utils/rollup-plugins.js
This Rollup plugin is no longer necessary.
> Remove replacing TS @class with #__PURE__

- packages/react-universal/CHANGELOG.md
- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/router/createRouter.ts
- packages/router/src/side-effects/announce.ts
- packages/router/src/side-effects/scroll.ts
- packages/router/src/side-effects/title.ts
- packages/router/tests/createRouter.spec.ts
- packages/router/types/router/createRouter.d.ts
- packages/router/types/side-effects/announce.d.ts
- packages/router/types/side-effects/scroll.d.ts
- packages/router/types/side-effects/title.d.ts
- packages/static/tests/staticFiles.spec.ts
- packages/types/src/index.ts
- packages/types/types/index.d.ts
- packages/vue/.size-snapshot.json
- packages/vue/src/interface.ts
- packages/vue/src/plugin.ts
- packages/vue/types/interface.d.ts
- website/src/pages/Guides/sync-or-async.js
- website/src/pages/Packages/v2/router/api/createRouter.js
- website/src/pages/Tutorials/react-advanced.js
The initial values of `response` and `navigation` are now `undefined` instead of `null`. This only affects calls to `router.current` since observers are not called until a response has been created.
> response/navigation start out undefined, not null

- packages/react-dom/.size-snapshot.json
- packages/router/.size-snapshot.json
- packages/router/src/router/finishResponse.ts
- packages/router/src/router/typeGuards.ts
- packages/router/tests/createRouter.spec.ts
- packages/router/types/router/typeGuards.d.ts
This PR allows a user to provide a redirect `url` string instead of specifying the location to redirect to with a name/params. The user is expected to include any hash/query segments in the `url` string.
> Allow redirect: { url }

- packages/react-dom/.size-snapshot.json
- packages/react-dom/CHANGELOG.md
- packages/react-dom/src/Link.tsx
- packages/react-dom/types/Link.d.ts
- packages/react-native/.size-snapshot.json
- packages/react-native/CHANGELOG.md
- packages/react-native/src/Link.tsx
- packages/react-native/types/Link.d.ts
Fixes #237
The previous types included props that get passed to `useNavigationHandler` by the `Link` that the user doesn't actually provide themselves.
> Fix React Link types

- packages/router/.size-snapshot.json
- packages/router/CHANGELOG.md
- packages/router/src/prepareRoutes.ts
- packages/router/tests/createRouter.spec.ts
https://github.com/pshrmn/curi/issues/249
I elected to omit instead of including the property with an `undefined` value so that passing the params back to be compiled into a URL does not error.
> Omit undefined optional params from match params
